TaskManager/Models/ErrorViewModel.cs
namespace TaskManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TaskManager/Models/TaskItem.cs
namespace TaskManager.Models
{
    public class TaskItem
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Descripcion { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public bool IsCompleted { get; set; }
    }
}

TaskManager/Models/TaskListItem.cs
namespace TaskManager.Models
{
    public class TaskListItem
    {
            public List<TaskItem> Tasks { get; set; } = new(); 

    }
}

TaskManager/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Models;

namespace TaskManager.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TaskManager/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using TaskManager.Models;

namespace TaskManager.Controllers
{
    public class TaskController : Controller
    {
        public IActionResult Index()
        {
            var task = new TaskItem
            {
                Id = 1,
                Title = "Tarea cambiada",
                Descripcion = "Probando flujo controller + View",
                CreatedAt = DateTime.UtcNow,
                IsCompleted = true
            
            };

            return View(task);
        }
    }
}

TaskManager/Controllers/TaskListController.cs
using Microsoft.AspNetCore.Mvc;
using TaskManager.Models;
using TaskManager.Data;
using System.Security.Cryptography.X509Certificates;
namespace TaskManager.Controllers
{
    public class TaskListController : Controller
    {
        private readonly AppDbContext _context;
        public TaskListController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var tasks = _context.Tasks.ToList();
            return View(tasks);
        }

        public IActionResult Create(TaskItem task)
        {
            if (ModelState.IsValid)
            {
                _context.Tasks.Add(task);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(task);
        }
    }
}

TaskManager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManager</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="TaskList" asp-action="create">Nuevas Tareas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" id="footer-text"> >
            &copy; 2026 - TaskManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManager/Views/Task/index.cshtml
@model TaskManager.Models.TaskItem

<h1>@Model.Title</h1>

<p>@Model.Descripcion</p>

<p>Fecha de creacion : @Model.CreatedAt</p>

@if (Model.IsCompleted)
{
    <p>Estado: Completada</p>
}
else
{
    <p>Estado: Pendiente</p>
}

TaskManager/Views/TaskList/Create.cshtml
@model TaskManager.Models.TaskItem

<h2>Crear Nueva Tarea</h2>

<form asp-action="Create" method="post">
    <div class="mb-3">
        <label>Titulo</label>
        <input asp-for="Title" />
    </div>
    <div>
        <label>Descripcion</label>
        <input asp-for="Descripcion" />
    </div>
    <button type="submit">Crear Tarea</button>
</form>

TaskManager/Views/TaskList/Index.cshtml
@model List<TaskManager.Models.TaskItem>

<h1>Tareas desde la base de datos</h1>

<a asp-action="Create" class="btn btn-primary mb-3">Crear Nueva Tarea</a>>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Descripcion</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model){
            <tr>
                <td>@task.Title</td>
                <td>@task.Descripcion</td>
                <td>@(task.IsCompleted ? "✔" : "Pendiente")</td>

            </tr>
        }
    </tbody>
</table>"